a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type (a))
print('Só tem espaço',a.isspace())
print('É um numerico',a.isnumeric())
print('É alfabetico ',a.isalpha())
print('É alfanumerico ',a.isalnum())
print('É maiusculas',a.isupper())
print('É minusculas',a.islower())
print('esta capitalizada',a.istitle())